apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: sushmaskillmine/flask_app1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "database-1.cv8emuow4jfw.us-east-1.rds.amazonaws.com"  # Replace with your RDS endpoint
        - name: DB_USER
          value: "admin"                # Replace with your DB username
        - name: DB_PASSWORD
          value: "database1234"        # Replace with your DB password
        - name: DB_NAME
          value: "crafters"             # Replace with your DB name
